/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  'learning-paths': [
    {
      type: 'doc',
      id: 'learning-paths/index',
      label: '🗺️ Learning Paths',
    },
    {
      type: 'category',
      label: 'Extras (new topics)',
      collapsed: true,
      items: [
        'learning-paths/extras/ai-sdk-patterns',
        'learning-paths/extras/webhook-vs-streaming-vs-polling',
        'learning-paths/extras/context-management-patterns',
      ],
    },
  ],
  topicsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
