name: Docs quality
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        continue-on-error: true
        with:
          globs: "topics/**/*.md"

  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        continue-on-error: true
        with:
          args: "--cache --max-cache-age 1d --exclude 'linkedin.com|twitter.com|x.com|arxiv.org' topics/**/*.md"
